name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        working-directory: ./cra-ts-cosmos
        run: |
          npm ci
          npm run cosmos:export
      - name: Deploy 🚀
        working-directory: ./cra-ts-cosmos
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: cosmos-export